package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/abdussamadbello/echonext/examples/graphql-demo/graph/generated"
	"github.com/abdussamadbello/echonext/examples/graphql-demo/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	user := &model.User{
		ID:    fmt.Sprintf("%d", len(r.users)+1),
		Name:  input.Name,
		Email: input.Email,
	}
	r.users = append(r.users, user)
	return user, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	// Check if author exists (inline to avoid deadlock)
	var authorExists bool
	for _, u := range r.users {
		if u.ID == input.AuthorID {
			authorExists = true
			break
		}
	}
	if !authorExists {
		return nil, fmt.Errorf("author with ID %s not found", input.AuthorID)
	}

	post := &model.Post{
		ID:       fmt.Sprintf("%d", len(r.posts)+1),
		Title:    input.Title,
		Content:  input.Content,
		AuthorID: input.AuthorID,
	}
	r.posts = append(r.posts, post)
	return post, nil
}

// Author is the resolver for the author field.
func (r *postResolver) Author(ctx context.Context, obj *model.Post) (*model.User, error) {
	return r.GetUserByID(obj.AuthorID), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()
	return r.users, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	return r.GetUserByID(id), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()
	return r.posts, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()
	for _, p := range r.posts {
		if p.ID == id {
			return p, nil
		}
	}
	return nil, nil
}

// Posts is the resolver for the posts field.
func (r *userResolver) Posts(ctx context.Context, obj *model.User) ([]*model.Post, error) {
	return r.GetPostsByAuthorID(obj.ID), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Post returns generated.PostResolver implementation.
func (r *Resolver) Post() generated.PostResolver { return &postResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
